---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc-corebank
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-sc
  fileSystemId: ${EFS_COREBANK_ID}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-corebank
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-corebank
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-test-app-corebank
  namespace: default
  labels:
    app: efs-test-app
    account: corebank
spec:
  replicas: ${COREBANK_REPLICAS}
  selector:
    matchLabels:
      app: efs-test-app
      account: corebank
  template:
    metadata:
      labels:
        app: efs-test-app
        account: corebank
    spec:
      containers:
        - name: efs-test-app
          image: ${IMAGE_URI}
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: EFS_MOUNT_PATH
              value: "/mnt/efs"
            - name: ACCOUNT_TYPE
              value: "corebank"
            - name: AWS_REGION
              value: "${AWS_REGION}"
            - name: WRITE_TIMEOUT
              value: "${WRITE_TIMEOUT}"
          volumeMounts:
            - name: efs-storage
              mountPath: /mnt/efs
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-pvc-corebank

---
apiVersion: v1
kind: Service
metadata:
  name: efs-test-app-corebank-service
  namespace: default
  labels:
    app: efs-test-app
    account: corebank
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: efs-test-app
    account: corebank

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-corebank
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${EFS_COREBANK_ID}
  mountOptions:
    - iam
